#!/usr/bin/env bash
#
# Rebuilds the whole database into a fresh Supabase project.
#
# Everything the old project held was generated by scripts, so recovery is
# replaying them in order — no data is lost that isn't reproducible. The videos
# live in S3 and are not touched.
#
#   ./supabase/recover.sh 'postgresql://postgres.<ref>:<pw>@aws-1-<region>.pooler.supabase.com:5432/postgres'
#
# Get that string from: Supabase Dashboard → Connect → Session pooler.

set -euo pipefail

DB_URL="${1:-${DATABASE_URL:-}}"
if [ -z "$DB_URL" ]; then
  echo "usage: $0 '<postgres connection string>'" >&2
  echo "       (Dashboard → Connect → Session pooler)" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

say() { printf '\n\033[1m%s\033[0m\n' "$1"; }

say "1/4  Schema, modules migration and starter seed"
psql "$DB_URL" -v ON_ERROR_STOP=1 -q -f supabase/APPLY_ALL.sql
echo "     ✓ tables created"

say "2/4  Mirror content (pestorspointers.com look)"
psql "$DB_URL" -v ON_ERROR_STOP=1 -q -f supabase/seed_mirror.sql
echo "     ✓ pages, blocks, nav, footer, brand"

say "3/4  Courses, modules and video rows"
# link-videos.js reads DATABASE_URL and the AWS keys from server/.env. It is
# idempotent: re-running updates rather than duplicating.
( cd server && DATABASE_URL="$DB_URL" node scripts/link-videos.js )

say "4/4  Verify"
psql "$DB_URL" -tA -c "
select 'pages    = '||(select count(*) from pages)
union all select 'blocks   = '||(select count(*) from page_blocks)
union all select 'settings = '||(select count(*) from site_settings)
union all select 'courses  = '||(select count(*) from courses)
union all select 'modules  = '||(select count(*) from modules)
union all select 'videos   = '||(select count(*) from videos);"

cat <<'DONE'

Done. Expected: 6 pages, 17 blocks, 3 settings, 3 courses, 34 modules, 418 videos.

Still to update by hand — the new project has different credentials:
  server/.env         SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, DATABASE_URL
  client/.env.local   NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY, SUPABASE_SECRET_KEY
  Amplify console     the same NEXT_PUBLIC_* values, plus API_URL once the API is deployed
DONE
